export const ACTUALIZAR = "PUBLICACIONES_ACTUALIZAR";
export const PUBLICACIONES_CARGANDO = "PUBLICACIONES_CARGANDO";
export const PUBLICACIONES_ERROR = "PUBLICACIONES_ERROR";
export const COMENTARIOS_CARGANDO = "COMENTARIOS_CARGANDO";
export const COMENTARIOS_ERROR = "COMENTARIOS_ERROR";
export const COMENTARIOS_ACTUALIZAR = "COMENTARIOS_ACTUALIZAR";
