export const TRAER_TODAS = "TAREAS_TRAER_TODAS";
export const CARGANDO = "TAREAS_CARGANDO";
export const ERROR = "TAREAS_ERROR";

export const CAMBIO_USUARIO_ID = "CAMBIO_USUARIO_ID";
export const CAMBIO_TITULO = "CAMBIO_TITULO";
export const TAREA_AGREGADA = "TAREA_AGREGADA";

export const ACTUALIZAR_TAR = "ACTUALIZAR_TAR";
export const LIMPIAR = "TAREAS_LIMPIAR";
